### ISSUE TITLE
1.3.1.11 Error file hash crc

### ISSUE THREAD

**Issue by 233lol** [Yutaka-Sawada/MultiPar#11]
Error file hash crc
CPU: 3900x
system: win10 2004
but 1.3.1.1 can create file

**Comment by Yutaka-Sawada** [comment]
Thank you for bug report. The error seems to be same as an incident on another thread.
https://github.com/Yutaka-Sawada/MultiPar/issues/3#issuecomment-702004198
https://github.com/Yutaka-Sawada/MultiPar/issues/3#issuecomment-703188914

I made a sample to test the problem. I put the sample (par2j_sample_2020-10-04.zip) in "MultiPar_sample" folder on [OneDrive](https://1drv.ms/u/s!AtGhNMUyvbWOaSo1n_R8awJ_hg0?e=4V0gXu). Please test it in your usage.

If new version works, I will release next version soon.

**Comment by Yutaka-Sawada** [comment]
Though I don't know the problem is solved in the sample version, I released new version as v1.3.1.2 today. If there is a problem still, please report again.

**Comment by 233lol** [comment]
> Though I don't know the problem is solved in the sample version, I released new version as v1.3.1.2 today. If there is a problem still, please report again.

There is no problem with this version..
