### ISSUE TITLE
What are /rd and /sr ?

### ISSUE THREAD

**Issue by SiddharthManthan** [Yutaka-Sawada/MultiPar#114]
I canot undersetand what those two options do. If I run par2j without specifying these options, will it use the defaults used by multipar ?

**Comment by Yutaka-Sawada** [comment]
> If I run par2j without specifying these options, will it use the defaults used by multipar ?

No, `/rd` may not. `/rd` option is same as `Sizing scheme` on Create window. The default of MultiPar is `All the same size` or `Powers of 2 sizing scheme`, which depends on existence of the item. If you see `Sizing scheme` item on MultiPar, `All the same size` is the default, which is same as setting `/rd0`. You may see the result by pushing `Preview` button on MultiPar or `test` command of par2j.

Yes, `/sr` is same default value in MultiPar. The item is `Rate (count /size)` in `Block allocating method` section on 
`GUI options` tab of MultiPar Options. Setting `/sr10` is same as setting `1%` on MultiPar. par2j supports wider range than MultiPar.

**Comment by SiddharthManthan** [comment]
Ok, Thank you very much.
