### ISSUE TITLE
Commandline increase thread count

### ISSUE THREAD

**Issue by SiddharthManthan** [Yutaka-Sawada/MultiPar#116]
How to increase threadcount for generating par file when using commandline ? Currently it uses half of total threads.

**Comment by SiddharthManthan** [comment]
Did not want to create another issue, so asking here, does generation using commandline automatically add files from subdirectory ?

**Comment by Yutaka-Sawada** [comment]
> How to increase threadcount for generating par file when using commandline ?

Use `/lc` option to set number of using threads. If you want to use max number of threads for your CPU, set `/lc32`. At this time, `par2j64.exe` supports max 32 threads. 32-bit version `par2j.exe` supports max 16 threads. If you want to use more threads than 32, you need to modify the limit value and re-compile par2j from source code. (Internally, it can control max 250 threads.)

> does generation using commandline automatically add files from subdirectory ?

par2j supports wild card. It supports recursive search. It's possible to disable recursive search by `/fo` option. You may use `/fa` and `/fe` options to allow/deny specific files at searching. For detail usage, refer "Command_par2j.txt" in "help" folder of MultiPar.

**Comment by SiddharthManthan** [comment]
Thank you very much.
> For detail usage, refer "Command_par2j.txt" in "help" folder of MultiPar.

Please add to github readme that this file exists. I didn't know about this file (didn't find it as it is in subfolder).
