### ISSUE TITLE
How to verify multi .par2 files located in multi folder using the gui multi par in a single window 

### ISSUE THREAD

**Issue by DEVUVO** [Yutaka-Sawada/MultiPar#118]
How to verify multi .par2 files located in multi folder using the gui multi par in a single window 

If every folder have it's own file and each folder has its own par2 files .

Thank you.

**Comment by Yutaka-Sawada** [comment]
Some users requested such feature ago. I made a Queue application with Python script language. In MultiPar's "Help documents", open "Python script" page, and read "Verify multiple PAR2 sets in a selected folder with Queuing GUI" item. You may modify the "queue_verify.py" file for your usage.

**Comment by DEVUVO** [comment]
Where to find the Help documents and Python script ? I don't see any page have read the help files and nothing in there , I think I'm lost .

**Comment by Yutaka-Sawada** [comment]
Under "MultiPar" folder, there is "help" folder. English pages exist in "0409" folder. Sample Python scripts exist in "tool" folder. When you use MultiPar, you may open "Help documents" by pushing F1-key.
