### ISSUE TITLE
No "par2_rename.exe" ?

### ISSUE THREAD

**Issue by uxmy** [Yutaka-Sawada/MultiPar#119]
I just realized that since v1.3.2.5, par2_rename.exe is not available. Does it means I can rename using par2j.exe, or you simply forgot to add that file to the latest installers ?

**Comment by Yutaka-Sawada** [comment]
> Does it means I can rename using par2j.exe, or you simply forgot to add that file to the latest installers ?

par2j doesn't support renaming. I replaced "par2_rename.exe" tool with "par2_rename.py",which was made in Python script language. So, I don't include "par2_rename.exe" now. You may use it in old versions still.
