### ISSUE TITLE
Error: save-directory is invalid

### ISSUE THREAD

**Issue by IndustrialOne** [Yutaka-Sawada/MultiPar#124]
I copy-pasted the exact commandline the GUI used:

"C:\Program Files\Multipar\par2j64.exe" c /uo /ss716800 /rn749 /vs1 /vdsave /rf1 "C:\bw2c4.mov.par2" "C:\bw2c4.mov"

Parchive 2.0 client version 1.3.2.6 by Yutaka Sawada

save-directory is invalid

The save directory is very much valid.

**Comment by Yutaka-Sawada** [comment]
The error means that "save" directory (specified by option `/vdsave`) doesn't exist. At creation, you don't need to set `/vs` nor `/vd` options mostly. MultiPar GUI sets them only to erase old verification results. Then, you just remove the options in your command-line. If you verify by command-line, make "save" directory under the same directory as "par2j64.exe".

**Comment by IndustrialOne** [comment]
Thanks, this worked.

What also works is getting rid of the quotes (and path) on the file, it turns out I added that while editing my workflow, my bad.
