### ISSUE TITLE
'File' and 'MD5' on MultiPar 1.3.1.2 beta are wrong

### ISSUE THREAD

**Issue by TheIncantation** [Yutaka-Sawada/MultiPar#14]
こんにちは  Yutaka Sawada san (I hope I do this the right way).

On your homepage, MultiPar 1.3.1.2 beta 'File' is "MultiPar1311.zip" which must probably be "MultiPar1312.zip" and same with "MultiPar1311_setup.zip" which must probably be "MultiPar1312_setup.zip".

**Comment by Yutaka-Sawada** [comment]
I see. Thank you for pointing my mistake. I corrected the filenames.
