### ISSUE TITLE
PAR3 create support

### ISSUE THREAD

**Issue by extesy** [Yutaka-Sawada/MultiPar#17]
Greetings @Yutaka-Sawada. I know that multipar can support reading par3 files, but there are no programs that I know of that can actually create it. Are you planning to add par3 support to multipar in the foreseeable future? If not then what does supporting par3 even mean in this case?

**Comment by Yutaka-Sawada** [comment]
> Are you planning to add par3 support to multipar in the foreseeable future?

 I cannot say, because PAR3 isn't made yet. You would better ask to Michael Nahas. He is important than me.

> If not then what does supporting par3 even mean in this case?

 There may be no program, which supports PAR3. If someone proposes a new plan as a next PAR3 specification, I will consider.

**Comment by extesy** [comment]
@mdnahas Michael, can you please confirm or deny if PAR3 is still being work on?

**Comment by extesy** [comment]
@Yutaka-Sawada I found out from https://github.com/Parchive/par2cmdline/issues/130 that
