### ISSUE TITLE
Blurry UI on secondary screen

### ISSUE THREAD

**Issue by thany** [Yutaka-Sawada/MultiPar#19]
The UI is blurry on my secondary screen.

My setup:
Monitor 1 (primary): 27" 4K set to 200% zoom
Monitor 2 (secondary): 19" SXGA set to 100% zoom
Windows 10 20H2

The UI is fine on the primary monitor. The UI would also be fine when using *only* the secondary monitor, having disconnected the primary.

It seems the UI is rendered at the zoom level of the primary monitor, but when displayed on another monitor it is somehow scaled down pixel-by-pixel or something, instead of rendering at the zoom level of that monitor.

Most other programs render perfectly crisp on my secondary monitor.

I have not yet tried any compatibility settings, because they should be neccesary only for old software.

MP also wants to *always* start on the primary monitor. It tries to "remember" its position, but never starts itself on the secondary monitor, even if that's where the last position was. I dunno if this is related, but I thought I'd mention it, because it also has to do with multiple monitor setups.

Please note, in order to test 4K zoom level, you **do not need a 4K monitor**. You can just set any monitor to a higher zoom, even 150% should show the issue. And then leave your secondary monitor at 100%.

**Comment by Yutaka-Sawada** [comment]
> The UI is blurry on my secondary screen.

 Thank you for bug report. The problem happens, when you uses multiple monitors. This is because current MultiPar doesn't support multiple monitors. 

> MP also wants to *always* start on the primary monitor.

 This behavior is same as above reason. It checks primary monitor only, and will set self position to inner of the primary desktop. 

 The most problem is that I don't know how multiple monitors looks. I don't have a secondary monitor. Though I find some developer information on the Internet, I cannot test the method on my PC. It will be difficult to support multiple monitors. It will be more difficult to support multiple monitors of different DPI. 

 So, it's good to use MultiPar on your primary monitor. I'm sorry for the inconvenience.

**Comment by thany** [comment]
> This is because current MultiPar doesn't support multiple monitors.

No offense, but there is nothing to support. If an application does nothing with multiple monitor, the OS will take care of everything, and it'll "just work".

So either it deliberately unsupports multiple monitors (which I seriously doubt), or a framework you're using is throwing spanners in the works (more likely the case). Perhaps updating that framework/library/toolkit might do the trick.

Either way, this is more of a bug than a "not supported" case, iyam.

> The most problem is that I don't know how multiple monitors looks. I don't have a secondary monitor. 

Yeah that's a bit of a problem then. I though most developers have two monitors, or at least have some old garbage leftover monitor knocking around 😀

> It will be more difficult to support multiple monitors of different DPI.

Like I said, setting the zoom level different for each monitor will already trigger the problem. You don't need physically different DPI's.

**Comment by Yutaka-Sawada** [comment]
I found an API to get information of secondary monitor. It will be possible to open MultiPar on a secondary monitor. I made a sample to test.

I put the sample (gui_sample_2021-01-01.zip) in "MultiPar_sample" folder on [OneDrive](https://1drv.ms/u/s!AtGhNMUyvbWOaSo1n_R8awJ_hg0?e=4V0gXu). Please test it, if someone has multiple monitors. If there is a problem, please notice me.


> It seems the UI is rendered at the zoom level of the primary monitor, but when displayed on another monitor it is somehow scaled down pixel-by-pixel or something, instead of rendering at the zoom level of that monitor.

Does someone send me sample screen-shots of such blurry windows ? Sample of good rendering application is required, too. I'm not sure how it looks bad and how it should be.

**Comment by JohnLGalt** [comment]
I'll test in next couple of days.  I use dual monitors, both same identical type, but I would prefer for MultiPar to open on secondary monitor.

**Comment by Yutaka-Sawada** [comment]
> I'll test in next couple of days.

Thank you for help. I will release next version after the test.

**Comment by JohnLGalt** [comment]
I just tested - both the current version and the sample still force open on the first monitor.  If I drag the window to the second monitor, then the next time the program is opened it is opened to the farthest left point of the first monitor (I have my main monitor on right, and secondary monitor on the left, and my Windows Display extends leftwards).

So, I'm not sure if my existing settings might be causing the new version to override it's default behavior - as I don't actually install MultiPar, but use the .ZIP download extracted to a location on my HD.  I *did* extract the new sample to a *different* folder (and then ran it in there without copying any old information from the existing folders), but perhaps my settings in my User profile folder are still overriding the behavior?

**Comment by JohnLGalt** [comment]
Animated GIF showing what is happening:

https://photos.app.goo.gl/orByqq1ZX9MMPVV27

Interesting to note that the pop-up window for about Multi par now follows the main window location, which is a significant improvement over existing release.  So you've made a lot of good progress with this test build.

If you need any more information, please do not hesitate to ask.

**Comment by Yutaka-Sawada** [comment]
> I just tested - both the current version and the sample still force open on the first monitor.

Thank you for tests. It's ok to run sample MultiPar.exe on another folder. If you want, you may copy setting file "MultiPar.ini" from main installed folder. The animation is good to see and understand what happened. It seems to fail locating MultiPar's main window position at first time. I changed the method to find the nearest monitor from Window Handle to direct Point value. 

I put the sample (gui_sample_2021-01-10.zip) in "MultiPar_sample" folder on [OneDrive](https://1drv.ms/u/s!AtGhNMUyvbWOaSo1n_R8awJ_hg0?e=4V0gXu). Please test it again. If you have time, please check the position of Preview window, too. The Preview window has relative position from Create window.

**Comment by JohnLGalt** [comment]
Latest sample opens where it was closed.  Options window still follows location of main window.

I will test more thoroughly with all windows and popups to be sure, but it seems like this is fixed now.

**Comment by Yutaka-Sawada** [comment]
> Latest sample opens where it was closed.

Thanks ! It's a good news.

> I will test more thoroughly with all windows and popups to be sure, but it seems like this is fixed now.

How do you think about Folder Selecting dialog, which is opened by "Browse" button ? At previous versions, I didn't move the position of the dialog. By default, the dialog location seems to be center of desktop always on my PC. When there are multiple monitors, I don't know where it goes. If you put MultiPar on a secondary monitor and folder selecting dialog may pop-up on a main monitor, it will be bad usability.

Technically, the folder dialog is possible to follow location of main window, too. It's near to center of parent window. Because a user may change the size of folder dialog, it's hard to centering precisely. When you are interested in the position of Folder Selecting Dialog, I made a sample. I put the sample (gui_sample_2021-01-16.zip) in "MultiPar_sample" folder on [OneDrive](https://1drv.ms/u/s!AtGhNMUyvbWOaSo1n_R8awJ_hg0?e=4V0gXu).

**Comment by JohnLGalt** [comment]
I tested with official 1.3.1.3 release, unofficial sample 1.3.14 release from 01 Jan (the older one) and unofficial 1.3.1.4 release from 10 Jan (the newer one).

**Add Files** button at left and **Open** button at bottom all open wherever main application window currently is.  **Browse** button opens in middle of whichever screen Multi-Par main screen is located.

If you could get that one **Browse** button to also follow exact window location, that would be helpful.

I will get the new sample and try it next.

**Comment by JohnLGalt** [comment]
I tried new 16 Jan build, and it is better - it does, indeed, try to find the relative center of main application windows.  

- With main window at minimum width and height, **Browse** dialog box found relative center of main application window.
- With main window at double minimum width and minimum height, **Browse** dialog box found relative center of main application window.
- With main window at minimum width and double minimum height, **Browse** dialog box found relative center of main application window.
- With main window at double minimum width and height, **Browse** dialog box found relative center of main application window.

Special case - if main application window spans across multiple screens, it gets tricky - it tries to find center of main application window, but at a certain threshold (haven't figured out exactly how much) it will find center of larger part of main application window and center on that larger part.  For instance, if main window is 70% on left screen and 30% on right screen, **Browse** dialog box found relative center of the 70% portion of the main application window.  But if it is close to 50% on both screens, then **Browse** dialog box found relative center of main application window, which means it also spans both screens.

I will try to make another animation of all of this in a little while to help illustrate.  However, I can say this - as is, this latest (16 Jan) sample is ***vastly*** superior to the current 1.3.1.3 in terms of window and dialog-box placement.  The minor issue with spanning multiple screens is so tiny that it should not cause any real problems for anyone.

**Comment by JohnLGalt** [comment]
Correction:  In the above special case - this only happens if the larger part is on the primary screen, at which case the **Browse** dialog box appears on the primary screen, just as the current 1.3.1.3 Options dialog box does.  if the majority is not on the primary screen, then the dialog box now finds the center of the main application window.

I will make an animation of this special case - it's even less prominent than what I previously described, so should happen almost never unless that user forces the main window to span across multiple screens such that more than 50% is on the primary screen.

**Comment by Yutaka-Sawada** [comment]
> If you could get that one Browse button to also follow exact window location, that would be helpful.

Oh, I see. I changed the behavior of positioning Folder Selecting dialog to be similar to File Selecting dialog. The same behavior will be good experience for users to see where a dialog opens. I put the new sample (gui_sample_2021-01-17.zip) in "MultiPar_sample" folder on [OneDrive](https://1drv.ms/u/s!AtGhNMUyvbWOaSo1n_R8awJ_hg0?e=4V0gXu). 


> The minor issue with spanning multiple screens is so tiny that it should not cause any real problems for anyone.

Auto-adjusting position is difficult for resizable window. (It might refer original window size instead of current window size.) I'm sorry for complex behavior and tests. Thus, at the new sample, I removed the centering method for the dialog. Now, it opens a Folder Selecting dialog just under the parent window. If the parent window spans multiple monitors, the dialog will spans, too. This is simple, and maybe easy to control for users.

**Comment by JohnLGalt** [comment]
It still does the offset if more than 50% of main application window is on primary screen.

But other than that it finds the main application window just as the other two file explorer windows do.

**Comment by Yutaka-Sawada** [comment]
> It still does the offset if more than 50% of main application window is on primary screen.

Thank you for quick test. I improved a method to adjust window position. It will check another monitor, when a window is partially outside of a monitor. This may work in most case. If there are many monitors of complex arrangement, it may fail. I put the new sample (gui_sample_2021-01-17b.zip) in "MultiPar_sample" folder on [OneDrive](https://1drv.ms/u/s!AtGhNMUyvbWOaSo1n_R8awJ_hg0?e=4V0gXu). Please test the case, which opens MultiPar window between two monitors.

**Comment by Yutaka-Sawada** [comment]
I refined the adjusting method. Now it checks working area of both primary and secondary monitors. (It may recognize and will exclude Task bar area.) When there are 3 monitors or they are different size largely, it may fail to adjust position of window or dialog. But, I hope this will work mostly. I put the sample (gui_sample_2021-01-18.zip) in "MultiPar_sample" folder on [OneDrive](https://1drv.ms/u/s!AtGhNMUyvbWOaSo1n_R8awJ_hg0?e=4V0gXu).

**Comment by Yutaka-Sawada** [comment]
I seached about [supporting High DPI](https://docs.microsoft.com/en-us/windows/win32/hidpi/high-dpi-desktop-application-development-on-windows). Currently, MultiPar supports "System Aware", which was introduced in Windows Vista. Actually I did not do any special coding, but just I set dpiAware item to be "True" in application's manifest. Windows OS seems to take care of everything for High DPI automatically, as Mr. thany mentioned in his previous post. This works well on a primary monitor, but it may auto-resize blurry on a secondary monitor. The issue Mr. thany reported at first was this incident.

The latest High DPI system seems to be "Per-Monitor Aware (Version 2)", which was introduced in Windows 10 (1703). Though I can set the flag in application's manifest also, I'm not sure what will happen. Basically it's same as changing compatibility setting on .EXE file's property dialog. There may be something additional coding to adapt "PerMonitor V2", or OS will do, I don't know. If someone who has multiple monitors of different DPI, I may make samples of different setting. Then I will see what happens in each setting.

I found another method, "GDI Scaling", which was introduced in Windows 10 (1809). It's [a resizing scheme of less blur](https://blogs.windows.com/windowsdeveloper/2017/05/19/improving-high-dpi-experience-gdi-based-desktop-apps/). This can be enabled by gdiScaling flag in application's manifest. But, I'm not sure what happens with combining other DPI settings.

Anyway, I need someone's help to test and see result. I cannot test those behavior on my PC (Windows 7) myself.

**Comment by JohnLGalt** [comment]
Although I have a dual monitor setup, both are normally run at identical resolutions as they are identical monitors.

I can try to test the blurriness aspect by forcing a resolution change on on of the monitors, but I suspect I'll need to get a third test monitor to actually discern any difference.

In the meantime, I'll run tests again on the latest sample wrt the dialog box location based upon main application window location again.

**Comment by Yutaka-Sawada** [comment]
> I can try to test the blurriness aspect by forcing a resolution change on on of the monitors

Thanks. If you have trouble in your PC environment, no need to test busy. It's OK for me to ask someone who is in the case. Those who using multiple monitors of different DPI daily may be suitable to see strange behavior.

> I'll run tests again on the latest sample wrt the dialog box location based upon main application window location again.

I hope it will work well at last, hehe. I tried sometimes and learned much.

**Comment by JohnLGalt** [comment]
I found an older 4:3 monitor with completely different resolution.  I brought it home this evening - I can now fully test and see if this occurs or not.

**Comment by Yutaka-Sawada** [comment]
I'm not sure that my made sample works with three monitors. If you put monitors in odd alignment (like left and top side), there may be something problem. When you see a problem, please report. Then, I will try to solve as possible as I can. Thank you for your effort and aid.

**Comment by JohnLGalt** [comment]
I can temporarily disable one of my normal monitors and use 1 current monitor and 1 old monitor.  And then I can test with all 3.  I will also try to force different geometric orientations.

**Comment by Yutaka-Sawada** [comment]
I made 3 samples. Current SystemAware version. New PerMonitorV2 version for Windows 10 (1703) or later. New gdiScaling version for Windows 10 (1809) or later. They have different application manifest. (They are same except the manifest.) I put the sample (gui_sample_2021-01-22.zip) in "MultiPar_sample" folder on [OneDrive](https://1drv.ms/u/s!AtGhNMUyvbWOaSo1n_R8awJ_hg0?e=4V0gXu). 

If gdiScaling can be less blurry, it will be the best. As I'm lazy, I don't want to write many code, hehe. If OS will support different DPI automatically by PerMonitorV2 setting, it would be good. But, I don't know.
