### ISSUE TITLE
Future of MultiPar

### ISSUE THREAD

**Issue by asvc** [Yutaka-Sawada/MultiPar#2]
First of all, exciting to see MultiPar on GitHub! Fingers crossed there will be source-code and some lively contributions from the community.

Next, maybe it makes sense (especially in light of the recently closed MultiPar forums) to update `README.md` with the short list of things you need help with?

Thanks.

**Comment by vk496** [comment]
+1 for releasing the source code. Parity guarantee is very useful for archive purposes. And for long time archiving, be able to use some software/protocol in 30 years to read (recover in this case) the data is crucial.
