### ISSUE TITLE
Norton 360 Deletes Installer Version MultiPar1313_setup.exe

### ISSUE THREAD

**Issue by oopman2002** [Yutaka-Sawada/MultiPar#20]
After I download the installer version, Norton 360 scans it and then deletes as a virus?

**Comment by Yutaka-Sawada** [comment]
I don't know how it recognized. I used [VirusTotal](https://www.virustotal.com/gui/home/upload) to check. The miss-detection isn't my fault nor my business. You should ask customer center (or user support) of Norton 360.
