### ISSUE TITLE
[Request] Ability to view/share debug information for errors

### ISSUE THREAD

**Issue by MartinKlefas** [Yutaka-Sawada/MultiPar#25]
I recently created a Parity set for a large set of folders, and when I now try to open it I just get an error that says "Error: Cannot Parse Output (0x02)"

If I then click "Verify" I Get "Error: Malloc (12)".

It would be useful to be able to create a crash-dump of some kind so that I could then email it to you or post it here.

Thanks.

**Comment by Yutaka-Sawada** [comment]
MultiPar saves recent internal text automatically, when it shows error message. You may open the save folder by double-clicking text area under progress-bar on Verify window. Or you may click "Open this user's save folder" button in "Folder location" section, on "System settings" tab, on MultiPar Options window. But, the auto-log isn't full size. If you want to save full log of par2j's output, you check "Log output of clients" in "Common options" section, on "Client behavior" tab. 

The log file is a text format "MultiPar.log" in the save folder. You may send it to me by e-mail, or post here (when it's enough small). It will help me to solve the problem of your case. Please change setting and try again, then send the "MultiPar.log" file.

**Comment by MartinKlefas** [comment]
Thanks - it's really handy - it might even be useful to add this as a crash/error handler. I've seen other software that says something along the lines of "It would be really helpful if you could describe what you were doing and we'll send an email to the devs with the last logs".
Below/attached is the log from this particular occasion. I created a 15% parity file for a group of folders with 13,000 images or around 28GB of data. It won't open or verify
[MultiPar.log](https://github.com/Yutaka-Sawada/MultiPar/files/5990508/MultiPar.log)

**Comment by Yutaka-Sawada** [comment]
Thank you for bug report. I'm sorry for the inconvenience in error handling. 

I found what was wrong in my code. I didn't think someone made so many PAR2 files. It allocated memory area for max 512 PAR2 files, and failed to treat such 2000 over PAR2 files in your case. I fixed the problem by expanding memory area for more PAR2 files. Though I implemented a function to treat many source files, I forgot to support many PAR2 files ago. Now, it becomes to work well for 2000 over PAR2 and source files on my PC. 

I put the sample (gui_sample_2021-02-17.zip) in "MultiPar_sample" folder on [OneDrive](https://1drv.ms/u/s!AtGhNMUyvbWOaSo1n_R8awJ_hg0?e=4V0gXu). Please test it in your case. Though I didn't test so many files, it would work. If there is a problem still, please notify again.

**Comment by MartinKlefas** [comment]
This worked perfectly, thanks.
