### ISSUE TITLE
Multiple verification on SSD

### ISSUE THREAD

**Issue by Yutaka-Sawada** [Yutaka-Sawada/MultiPar#26]
I implemented a method to verify multiple source files on SSD. It checks multiple complete files at once. Incomplete files (damaged or missing files) are checked in single thread still, because it's very hard to synchronize each result. Even when multiple verification seems to work on my PC, I might miss something or forgot a rare case or happened to put bug. 

Because I don't have SSD, I need help of users who have SSD. I want to know that this new method is fast or not. When source files are on RAM (disk cache), it's fast on my PC. But, SSD is slower than RAM. How fast it will be actually is unknown yet. If you have SSD, fast CPU (4 or more Cores), and courage to try non-stable version, please test and post your result.

To compare a time of verification, you must use v1.3.1.4 as old version. Because I changed code of MD5 calculation in v1.3.1.4 ago, comparing with older one (v1.3.1.3 or before) is bad. If you use MultiPar GUI for test, you must change a setting of "Re-use verification result" to "Not used". When "Re-use verification result" is enabled, it just read old verification result and cannot see real speed. 

I put the sample (gui_sample_2021-03-03.zip) in "MultiPar_sample" folder on [OneDrive](https://1drv.ms/u/s!AtGhNMUyvbWOaSo1n_R8awJ_hg0?e=4V0gXu). Caution ! As this is early sample version, I don't know what will happen. Don't use this sample for daily usage. Be careful the risk and use this only for testing purpose.

**Comment by JohnLGalt** [comment]
So, Do a verification of a set of files (preferably a large set so that it takes a good amount of time, right?) and then use this version to first uncheck re-use verification result, and then re-verify and compare times?

Both should save logs, right?

**Comment by JohnLGalt** [comment]
OK, some interesting results.

First of all, I deleted existing log for 1.3.1.4 build.  Then I made sure reuse verification was turned off.

Here is log from 1.3.1.4:  
[MultiPar.log](https://github.com/Yutaka-Sawada/MultiPar/files/6077987/MultiPar.log)

Here are images of 1.3.1.4 verification test:
![3 March Test - 01](https://user-images.githubusercontent.com/7432512/109847815-9f185580-7c1d-11eb-8a44-838bc6e83214.png)
![3 March Test - 02](https://user-images.githubusercontent.com/7432512/109847834-a3447300-7c1d-11eb-8bf9-2532156ca18a.png)
![3 March Test - 03](https://user-images.githubusercontent.com/7432512/109847856-a6d7fa00-7c1d-11eb-89fa-50daa7030222.png)

The I extracted 3 March test build to another folder, copied my MultiPar.ini to that folder, and verified that there was no log (no save folder) and also reuse verification was turned off.
Log file from test build verification of same files:  
[MultiPar.log](https://github.com/Yutaka-Sawada/MultiPar/files/6078002/MultiPar.log)

And Images:
![3 March Test - 04](https://user-images.githubusercontent.com/7432512/109848116-e7d00e80-7c1d-11eb-8fc6-2c71b9ab5237.png)
![3 March Test - 05](https://user-images.githubusercontent.com/7432512/109848147-eef71c80-7c1d-11eb-9e58-80a98693e673.png)
![3 March Test - 06](https://user-images.githubusercontent.com/7432512/109848166-f3233a00-7c1d-11eb-8d60-411fb584c890.png)

As you can see, significantly faster.

However, As you can see, AVX is not showing enabled in test build, even though option is selected.  Still, a very nice, huge improvement!

**Comment by Yutaka-Sawada** [comment]
> So, Do a verification of a set of files (preferably a large set so that it takes a good amount of time, right?) and then use this version to first uncheck re-use verification result, and then re-verify and compare times?

Yes. Because MultiPar GUI saves verification result by default, I wrote the notice. 

> Both should save logs, right?

If there is no problem, log is not required. When there is a bug, such like a source file is ignored, the log is helpful to see detail of the incident. 

> As you can see, significantly faster.

Thank you for tests. It detected drive type as SSD, and verified 5 source files at once. It seems to be 3 times faster in their results. But, I'm afraid that there might be effect of disk cache. The 6 GB source data can fit RAM's disk cache area on your PC. 

Did you clear disk cache before each test ? Reading file data from SSD or RAM (disk cache) causes much difference. I use Sysinternals's RAMMap.exe utility. Menu -> "Empty" -> "Empty standby list" will erase cached data.

**Comment by JohnLGalt** [comment]
Ahhh, good idea.  I did not consider that.  I'll try with RAMMap Empty.  And empty temporary files folder also.

Be back shortly.

**Comment by JohnLGalt** [comment]
I did some further testing, and made it a bit more extensive.

First of all, I made the file set larger - I created a 7-zip archive, split at default 650 MB (CD), of 38 Iron Maiden albums encoded in FLAC (many of which are double or greater albums).  I created the archive set as follows:

![4 March Test 00](https://user-images.githubusercontent.com/7432512/110008301-91c89d00-7ce9-11eb-8857-7b884df30d68.png)

I then created a parity set of 10% of the resulting 22 GB archive set using 1.3.1.4:

[MultiPar - 4 March test creation.log](https://github.com/Yutaka-Sawada/MultiPar/files/6085711/MultiPar.-.4.March.test.creation.log)

The resulting archive set with parity set was in a folder on my SATA III SSD, a SanDisk model no. SDSSDHII960G - information can be gleaned from this Amazon listing:  https://www.amazon.com/SanDisk-2-5-Inch-SDSSDHII-960G-G25-Corsair-Mounting/dp/B01M8MF5ET

Then I tested verification with 1.3.1.4:

[MultiPar - 4 March test 1.log](https://github.com/Yutaka-Sawada/MultiPar/files/6085778/MultiPar.-.4.March.test.1.log)

![4 March Test 01](https://user-images.githubusercontent.com/7432512/110009147-99d50c80-7cea-11eb-8731-b8607c31350e.png)

After that, I used RAMMap to Empty standby list as you mentioned, used Windows 10 Storage settings to clear temporary files, and then navigated to %localappdata%\temp and deleted all files in the temp folder that the system would let me.

Then I test with 1.3.1.5 test build:

[MultiPar - 4 March test 1.log](https://github.com/Yutaka-Sawada/MultiPar/files/6085780/MultiPar.-.4.March.test.1.log)

![4 March Test 02](https://user-images.githubusercontent.com/7432512/110009315-d4d74000-7cea-11eb-9f49-355cf556ea1f.png)

I then copied the test folder with archive and parity set to another drive - my Sabrent Rocket NVMe 4 SSD (one of three, this one does not have any system or users folders on it - it is strictly for storage).  Details on drive available from https://www.sabrent.com/product/SB-ROCKET-NVMe4-1TB/1tb-rocket-nvme-pcie-4-0-m-2-2280-internal-ssd-maximum-performance-solid-state-drive/

After the copy, I used RAMMap to Empty standby list as you mentioned, used Windows 10 Storage settings to clear temporary files, and then navigated to %localappdata%\temp and deleted all files in the temp folder that the system would let me.

![4 March Test 03](https://user-images.githubusercontent.com/7432512/110009487-11a33700-7ceb-11eb-8c84-3a4b9ed5cef7.png)

I then verified the test folder on NVMe drive using 1.,3.1.4:

[MultiPar - 4 March test 2.log](https://github.com/Yutaka-Sawada/MultiPar/files/6085781/MultiPar.-.4.March.test.2.log)

![4 March Test 04](https://user-images.githubusercontent.com/7432512/110009501-17991800-7ceb-11eb-8b12-f1360cdd7954.png)

After that, I used RAMMap to Empty standby list as you mentioned, used Windows 10 Storage settings to clear temporary files, and then navigated to %localappdata%\temp and deleted all files in the temp folder that the system would let me.

Finally I tested verification in 1.3.1.5 test build on NVMe drive:

[MultiPar - 4 March test 2.log](https://github.com/Yutaka-Sawada/MultiPar/files/6085783/MultiPar.-.4.March.test.2.log)

![4 March Test 05](https://user-images.githubusercontent.com/7432512/110009581-34cde680-7ceb-11eb-87fd-3c34f2608a53.png)

So, there are the results.

It's not anywhere near 1:3 ratio, not really even 1:2, considering cache and other stuff.  But it *is* still a significant increase in speed when the system detects SSDs and makes use of the SSD programming.  On the slower SATA II SSD with no cache to rely on, it was just over a 25% increase in speed (22 seconds speed increase / 80 seconds total for 1.3.1.4).  

On NMVe the increase is significantly faster.  The time difference is 17 seconds, which is an increase of 37.78% (over 1/3) from 1.3.1.4.

Also, I should note that, for testing, both 1.3.1.4 and 1.3.1.5 test build were .ZIP archives extracted to the same NVMe SSD (different from the one where I copied the test folder to).  Same exact specs (I have 3 of those drives - one for system - aka Windows and programs, 1 for user data, and one for fast storage (mainly in use for VM storage).

I hope this helps.

**Comment by JohnLGalt** [comment]
And now I see that you have found an issue with SSD verification in another thread lol.  And that there is a new test build.  I'm still using 3 March test build.

I think at this point any more testing will have to wait until SSD verification bug is verified fixed (although nutpantz says it is and closed his bug) and 1.3.1.5 is properly released.

I'm available to test at a moment's notice, as I've left the test folder with archive and parity set intact on both drives.  However, if there is a bug, I have not seen it as it seems the parity files were created perfectly fine - verification in 1.3.1.4 and 1.3.1.5 test build 3 march had 0 issues.

if you have any suggestions as to how to vary the parity set I created, let me know - as I said, I'll keep the folders on both drives intact for further testing until this is resolved.

**Comment by Yutaka-Sawada** [comment]
Thank you for tests. Multiple verification seems to be faster on SSD. It's not big difference, but is a little faster. By the way, you don't need to create recovery blocks in this test. Checking PAR2 files is processed by single thread. Using redundancy 0 was enough.

> However, if there is a bug, I have not seen it as it seems the parity files were created perfectly fine

As you saw [another issue post](https://github.com/Yutaka-Sawada/MultiPar/issues/27), there was a bug in verification method. When there is no Input File Slice Checksum packet, it failed to calculate hash of the file correctly. Even when there is no checksum, it should have calculated MD5 hash. There were 2 bugs, failed to create Checksum packets, and failed to verify without Checksum. Because it happened only when a file size was multiple of block size, you didn't see the bug. 

> if you have any suggestions as to how to vary the parity set I created, let me know

I'm not sure how to set max number of threads. I set max 5 threads for creation process currently. From your test result, 2 or 3 threads might be enough for verification process. It will be good to see debug output. I made a sample with debug output. Please test the sample by enabling Log. Then post the verification time (no need to post whole log lines). Instead of comparing with old v1.3.1.4, you can change file access mode by adding a line "FileAccess=1" in MultiPar.ini file. The option forces single reading mode, even when the drive is SSD. So, I can see the time of old method with the option. I will set the max number by referring the result comparison.

I put the sample (gui_sample_2021-03-05.zip) in "MultiPar_sample" folder on [OneDrive](https://1drv.ms/u/s!AtGhNMUyvbWOaSo1n_R8awJ_hg0?e=4V0gXu).

**Comment by JohnLGalt** [comment]
OK, so, to make sure I understand:

Use this debug build, do verification and post only line from log with verification time.  Then add 'FileAccess=1" to MultiPar.ini and run verification again, and again post time.  Correct?

**Comment by Yutaka-Sawada** [comment]
Yes. Verify 2 times. Post their results in 1 time.

**Comment by JohnLGalt** [comment]
OK.

As for creating parity set - I had no set, I made that archive set myself from already extracted files.  So, I had to make parity set to test verify.  I only included the log so you would see the size of both archive set and parity set.

Testing now.

**Comment by JohnLGalt** [comment]
Tested with 5 March debug build.  

first test without FileAccess=1, time = 52 seconds.

Used RAMMap to clean, removed temp files, used Windows settings to delete temp files.

Second test with 'FileAccess=1', time = 52 seconds also.

Uh....

**Comment by Yutaka-Sawada** [comment]
I forgot to write. Remove the line "FileAccess=1" in another time. You need to reload MultiPar.exe to re-read .INI file.

If SSD info is shown like below, post the lines, too.
```
STORAGE_ADAPTER_DESCRIPTOR
Version = #, Size = #, BusType = #

DEVICE_TRIM_DESCRIPTOR
Version = #, Size = #, TrimEnabled = #

DEVICE_SEEK_PENALTY_DESCRIPTOR
Version = #, Size = #, IncursSeekPenalty = #
```

Core/Thread info, too.
```
cpu_num = #, entity_num = #, multi_read = #
```

**Comment by JohnLGalt** [comment]
so, verify without file access, then add it in and verify again, and then remove it once again and run one more time?

And I'll add those info the previous test now and then start with new log.

**Comment by Yutaka-Sawada** [comment]
I planned verify 2 times. One time is verification normally without "FileAccess=1" (case of auto-detection). Another time is verification with "FileAccess=1" (case of single thread mode). 

> Uh, that info you asked for is not being shown in log file anywhere.

Ohh, I forgot that. I updated sample file, gui_sample_2021-03-05b.zip in [OneDrive](https://1drv.ms/u/s!AtGhNMUyvbWOaSo1n_R8awJ_hg0?e=4V0gXu). I'm sorry for my mistake. Please test again.

**Comment by JohnLGalt** [comment]
No problem - I had a feeling that may be the case.  Does the 'FileAccess=1' parameter need to go under a specific section (like maybe [Verify]), or will it work no matter where it appears (at top, at bottom, etc.)?

**Comment by JohnLGalt** [comment]
OK, I ran 4 tests.  2 on SATA II SSD (Y:) and 2 on NVMe SSD (E:).  

**Methodology:**
Prior to **_every_** test (including the first test):

1. All programs were closed, except my file manager, Xplorer².
2. I opened RAMMap (through utility called WSCC) and performed Empty Standby List.  Both RAMMap and WSCC were left open.
3. I opened Windows 10 settings and from System --> Storage I selected and cleared "Temporary files".  I left Windows settings open.
4. I opened Windows Explorer to location %localappdata%\temp and select all items, then performed [SHIFT] + {DEL], skipping files that system would not let me delete.  I left Windows Explorer open.

The tests:

**SATA III SSD, _no FileAccess_:**

` STORAGE_ADAPTER_DESCRIPTOR
 Version = 32, Size = 32, BusType = 11

 DEVICE_TRIM_DESCRIPTOR
 Version = 12, Size = 12, TrimEnabled = 1
, SSD

 hash 42.985 sec, 498 MB/s`

**SATA III SSD, _FileAccess=1_:**

`hash 67.266 sec, 318 MB/s`

**NVMe drive, _no FileAccess_:**

` STORAGE_ADAPTER_DESCRIPTOR
 Version = 32, Size = 32, BusType = 17

 DEVICE_TRIM_DESCRIPTOR
 Version = 12, Size = 12, TrimEnabled = 1
, SSD

hash 23.203 sec, 922 MB/s`

**NVMe drive, _FileAccess=1_:**

` hash 42.844 sec, 499 MB/s`

Again, AVX2 is selected in Options by default, but does not show in log.

However, the really strange thing happens when I enable GPU acceleration.  Then times do not vary regardless whether FileAccess=1 is in MultiPar.ini or not - which makes sense.  All of the above had no GPU acceleration enabled.

**Comment by Yutaka-Sawada** [comment]
Thank you for tests and precise explanation. From their result, using 2 threads seems to be enough mostly. I will change the max number to be 2 or 3. Because the method for SSD is still trial period, I may change more from user's experience. 

SATA SSD : 56% improvement in the test -> It will use max 2 threads.
NVMe SSD : 84% improvement in the test -> It will use max 3 threads.


> Again, AVX2 is selected in Options by default, but does not show in log.

This isn't a bug. It doesn't use AVX2 in hash calculation. If you copy "par2j64_extra.dll" and put in the folder of "par2j64.exe", it shows the item. (I didn't put, as it's not used in this test case.)

> the really strange thing happens when I enable GPU acceleration.

I'm not sure what was wrong. It doesn't happen on me. Though I re-viewed my code, I could not find the reason. But, I might miss something. If you notice the problem again, please let me know.

**Comment by JohnLGalt** [comment]
Oh - I didn't even realize that x64 builds were not there nor being used.  Now it makes perfect sense.  My apologies!

I can try another set of tests, and post results again like above.  I suspect that, even though an older video card, my 970 GTX plus my current system work together very well for verification purposes.

**Comment by Yutaka-Sawada** [comment]
AVX2 or GPU doesn't affect hash calculation. They are used by encoder or decoder. (creating recovery blocks or repairing from recovery blocks) So, I felt that there might be a problem in updating .INI file. When MultiPar is installed under "program files" folder on Windows 10, the position of "MultiPar.ini" isn't the folder but user's independent directory.  

I made a way to know internal switch of file access mode. If you see a word of SSD at the last of a line "Memory usage" on MultiPar.log file, the "Base Directory" is recognized as SSD. Then, some parts of creation, verification, and repair, becomes processed by multi-thread or random access. These methods may improve speed on SSD, but is slow on HDD.

**Comment by JohnLGalt** [comment]
But I don't _install_ MultiPar.  I get .ZIP and extract it to a separate folder.  The regular version is extracted to folder `D:\Programs\MultiPar` that I create after Windows installation.  I only run MultiPar once as administrator to assign associations for par and par2 files, and after that I simply double click par / par2 file to start verification.  So MultiPar.ini file is located _locally_ within the same MultiPar folder, not in my `\Users` folder.  Having used multiple drives for well over 2 decades, this has been my _modus operandi_ for a long time.  I take it further, actually, in that I use an installation script to have Windows move `\Users` to a separate physical drive, so in effect, my `C:` drive only has `\Program Files (and (x86)`, `\System`, and `\ProgramData` and my `D:` drive has `\Users` - physically separated, making both reinstallations and clean installs a lot easier.

The test builds are downloaded to my Downloads folder (`D:\Users\{mylogin}\Downloads`) so it is on the same drive as the regular use version.  That also eliminates other variables when testing.  Both test and regular builds are .ZIP extracts with local .ini, and both are located on the same physical NVMe SSD.

**Comment by JohnLGalt** [comment]
OK, I tested again - I must have forgotten to clear standby pt in RAMMap the first time when I had GPU accelerate enabled.  I performed tests again with GPU acceleration enabled in exact same methodology as above 2 days ago and times were not identical at all.

My apologies about bringing GPU acceleration into discussion.

**Comment by Yutaka-Sawada** [comment]
There is no problem. Thank you for confirming the case.

**Comment by JohnLGalt** [comment]
Ver 1.3.1.5 is *definitely* faster than previous versions.  Thanks for all the work that you do for MP!

**Comment by r1cola** [comment]
Wow, I gotta try this out now also!  Sounds like just the thing i was looking for with my SSDs! :)

**Comment by JohnLGalt** [comment]
You should probably try the latest 1.3.1.8....
