### ISSUE TITLE
Demand of Compiled HTML Help ?

### ISSUE THREAD

**Issue by Yutaka-Sawada** [Yutaka-Sawada/MultiPar#30]
Because web browser is general software nowadays, I want to change format of Help documents to normal HTML files instead of Compiled HTML Help (.chm). Then, I don't need to install nor use the obsolate HTML Help Workshop on my new PC. Because it doesn't support Unicode, I must change PC's system language everytime. I'm not sure the usage works on Windows 10. 

Reading help on browser may be enough mostly. But, 2 features (Index and Search) will be lost on a simple html file. Does someone require such feature for Help documents ? 

Unless there is a strong demand of Compiled HTML Help, I won't compile HTML files from next help update. (I put current CHM files until future change.) I feel that most users never search a word among help files.

**Comment by JohnLGalt** [comment]
According to https://answers.microsoft.com/en-us/windows/forum/windows_10-files/cant-open-chm-file-on-win10/986830b0-8351-4a83-80e9-e24bf3f55ea4 Windows 10 still contains hh.exe to view .chm files.  I just verified that it exists on my machine.

That being said - if it makes MP development easier for you, I have no issues with converting to regular HTML - in fact, here on GitHub, you have Wiki section where you can place all the help stuff, and have it always accessible for your viewers.  You can also make it available for download for offline viewing if need be, and thus completely do away with the chm files completely.
