### ISSUE TITLE
MutliPar Portable won't run from folder with extended characters in name

### ISSUE THREAD

**Issue by JohnLGalt** [Yutaka-Sawada/MultiPar#33]
Hi, @Yutaka-Sawada .

As I've mentioned before, I run MultiPar portable from .ZIP extracted to folder named `MultiPar`.  For βeta builds I created a folder named `MultiPar βeta`.  However, MultiPar will not start, giving me the following error:

![MP Folder name issue 01](https://user-images.githubusercontent.com/7432512/118025008-58d22780-b32d-11eb-97cb-4362e65b546c.png)

If I change name to `MultiPar Beta` then MP works fine.

Tested with MP 1.3.1.5β, 1.3.1.6β and 1.3.1.7β - if "β" character (U+0382) is in filename, MP fails to start.

**Comment by Yutaka-Sawada** [comment]
Thank you for bug report. There is a problem in [Win32API MapFileAndCheckSum](https://docs.microsoft.com/en-us/windows/win32/api/imagehlp/nf-imagehlp-mapfileandchecksuma), which doesn't support Unicode chracaters in .EXE file's path. Even though the API accepts Unicode string, it may fail to translate them. Then, it could not find the path of .EXE file. It depends on which code-page you use. On my PC (Japanese), greek characters don't make problem. 

 I changed the function to CheckSumMappedFile in new sample. MapFileAndCheckSum is simple. CheckSumMappedFile requires opening a file and mapping to memory. Please test the new method. If CheckSumMappedFile works well, I will change "par1j.exe" and "sfv_md5.exe", too. I put the sample (MultiPar_sample_2021-05-13.zip) in "MultiPar_sample" folder on [OneDrive](https://1drv.ms/u/s!AtGhNMUyvbWOaSo1n_R8awJ_hg0?e=4V0gXu).

**Comment by JohnLGalt** [comment]
That build worked perfectly fine from folder named `MultiPar βeta`, as well as a folder named `βΈΈΌΛƉǄ^©§ըչ֍ᴱᵀᴟᴁ`.

I think this bug is solved.  Closing.
