### ISSUE TITLE
GPU Acceleration via par2j64.exe???  Is it possible?  How do I do it?

### ISSUE THREAD

**Issue by Neltulz** [Yutaka-Sawada/MultiPar#40]
Hi, I am used to using the MultiPar GUI, with GPU acceleration enabled.  I save lots of time by enabling this (Approximately 1 minute and 13 seconds of saved time for a 16GB input file).

## Question: 
Is there a way that I can:  **forcibly enable GPU Acceleration** from the par2j64.exe?

## My configuration:

> Redundancy: 5%
> Number of Recovery Files: 10

## My script is:
(Using Javascript in Directory Opus File Manager):
```javascript
par2j64 = '"C:\\Users\\Neil Moore\\AppData\\Local\\MultiPar\\par2j64.exe"';

cmdToRun = par2j64 + ' create /rr5 /rf10 "{sourcepath$}_par2\\{filepath$|nopath|noext}" {filepath$}';

cmd.RunCommand(cmdToRun)
```

## Resulting Command that is passed to Command Prompt:
```
"C:\Users\Neil Moore\AppData\Local\MultiPar\par2j64.exe" create /rr5 /rf10 "Q:\__Plex\_Movies\Tenet (2020)\_par2\tenet_sample" "Q:\__Plex\_Movies\Tenet (2020)\tenet_sample.mkv"
```

Thank you for your hard work on this program!

**Comment by Yutaka-Sawada** [comment]
There is a help document (Command_par2j.txt) in "help" folder under MultiPar's installed folder. You may refer it for details of options. To enable GPU acceleration at command-line, set "/lc32" option.

**Comment by Neltulz** [comment]
Ah, thank you.  I was confused.  I was looking for an option called /gp or something, for "enable GPU acceleration".
