### ISSUE TITLE
recovery blocks

### ISSUE THREAD

**Issue by HardcoreGames** [Yutaka-Sawada/MultiPar#41]
I notice that recovery blocks are exponential growing in size, this is not a good idea as smaller recovery files are less likely to be lost compared to larger ones

I use Par2 to secure computer chess files which amount to 1.12 TB for retrograde 6-pieces perfect chess

disk errors can damage the set so I use redundancy to secure the set

6-pieces
6-pieces.vol000+01
6-pieces.vol001+02
6-pieces.vol003+04
6-pieces.vol007+08
6-pieces.vol015+16
6-pieces.vol031+32

some restraint in exponentially larger blocks is a wiser course of action

**Comment by Yutaka-Sawada** [comment]
> some restraint in exponentially larger blocks is a wiser course of action

There is a way to limit size of Recovery Files. It's the number of blocks in the largest source file by default. 

From Help documents of MultiPar;
Each recovery file will be smaller than the largest source file (or splited source files).

For example, if the largest source file contains 16 source blocks, each recovery file includes max 16 recovery blocks. The result will be like below;
6-pieces
6-pieces.vol000+01
6-pieces.vol001+02
6-pieces.vol003+04
6-pieces.vol007+08
6-pieces.vol015+16
6-pieces.vol031+16
6-pieces.vol047+16

When all source files are very large, recovery files may become large, too. This might be your case. For the case, it's possible to set the limit size manually. 

After selecting source files, check "Split Files" check-box on Create window. While "Limit Size to" edit-box is enabled, you can type the max size. This value will become the max size (of splited source files). Then, un-check the "Split Files" check-box not to split source files actually. Even though it won't split source files now, the max value was set already. By this way, you can set favorite max size for recovery files.

**Comment by HardcoreGames** [comment]
Only reason I bring it up is to have more safety with a smaller redundancy. I am using 2% recovery for the chess folder to prevent losses from disk errors which are all too common lately.
