### ISSUE TITLE
Linux/macOS support

### ISSUE THREAD

**Issue by Safihre** [Yutaka-Sawada/MultiPar#53]
As I have not seen any issue for it, I will open one here.

If you could add Linux support, this would be amazing for many users. This would also add macOS support in 1 go!
It would not need a GUI, just the command-line interface would be enough for Linux users.

We (SABnzbd) donated before and if it helps development of a Linux version, we will gladly donate a couple of more times! 💯

**Comment by Yutaka-Sawada** [comment]
> It would not need a GUI, just the command-line interface would be enough for Linux users.

I'm not sure what is a good point of using my PAR2 client on other OSes. Current my source code is written in Microsoft C and Win32API. (It's not C++, as my programming skill is primary level.) Though I can write a simple tool with standard C language for other OSes, it will be slow and has limited feature only. Full conversion from Win32API to POSIX style is impossible. My PAR2 client is open source, and anyone can modify it. If it's possible, another programmer would do already.

Then, you would better use a general tool; [par2cmdline](https://github.com/Parchive/par2cmdline). For creation, you may use a special tool; [ParPar](https://github.com/animetosho/ParPar). If you want a feature in those PAR2 clients, you may request it on their development forum.

**Comment by Safihre** [comment]
The point would be the performance, and in our case specifically the verification and repair performance because Multipar utilizes CPU and GPU optimizations.
I would imagine this core functionality does not depend on the platform? Only for example file input/output is OS-specific.

**Comment by Yutaka-Sawada** [comment]
I'm sorry, but I don't want to try. I don't use Linux OS. To get performance, I need to develop and test on Linux PC by myself. I'm too lazy. Please ask another programmer, who is using Linux or Mac.
