### ISSUE TITLE
No joining when there is damage

### ISSUE THREAD

**Issue by Safihre** [Yutaka-Sawada/MultiPar#56]
We noticed that if Multipar detects a split-set, it automatically joins the files.
However, if one of the parts is damaged, it only repairs and doesn't do the joining.

Is that on purpose?

**Comment by Safihre** [comment]
Run repair on this set: [filejoin.zip](https://github.com/Yutaka-Sawada/MultiPar/files/7808339/filejoin.zip)
Results in 1 file `par2test.bin`
Run repair on this set: [filejoin.zip](https://github.com/Yutaka-Sawada/MultiPar/files/7808344/filejoin.zip) (1 file missing compared to set above)
Results in the repaired 11 `.00X` files and it did not join them.

**Comment by Yutaka-Sawada** [comment]
> Is that on purpose?

No, it's not. I don't know why it did so at your test. It can join pieces of a source file, only when all pieces exist. If one piece was lost, it needs to recover the piece at first to reconstruct the source file. The result should be same repaired source file.

> Results in the repaired 11 .00X files and it did not join them.

This is strange. On my PC, it repaired `par2test.bin`, as same as above test set.

**Comment by Safihre** [comment]
You are right, I mistook the output of my test.
Sorry.
