### ISSUE TITLE
Subfolders cause error

### ISSUE THREAD

**Issue by SJ-Innovation** [Yutaka-Sawada/MultiPar#60]
Unable to create PAR files for folders containing subfolders, error just says "GetFileAttribute failed" and computation stops.

**Comment by Yutaka-Sawada** [comment]
Thank you for bug report. I found some bugs in sanitizing functions, which I added at the previous version. I fixed the problem.

I put the sample (MultiPar_sample_2022-02-05.zip) in "MultiPar_sample" folder on [OneDrive](https://1drv.ms/u/s!AtGhNMUyvbWOaSo1n_R8awJ_hg0?e=4V0gXu). Please test the behavior. If there is a failure still, let me know again.

**Comment by SJ-Innovation** [comment]
Seems to have worked! Cheers
