### ISSUE TITLE
How to create one par file for each subfolder?

### ISSUE THREAD

**Issue by RichardJECooke** [Yutaka-Sawada/MultiPar#65]
Is there a to make the 'create' button create one .par file for each folder in the base folder?

I'm making par files for many gigabytes, and if I want to make a change to a subfolder, I don't want to have to recalculate the entire par file.

**Comment by Yutaka-Sawada** [comment]
> Is there a to make the 'create' button create one .par file for each folder in the base folder?

You may use Batch script for such routine task. I wrote a sample script. I will update an item of Batch script on MultiPar's help later.

Copy and paste below code on a text file. Edit the line for path of `MultiPar.exe` on your PC. Rename the text file to be such like `CheckPAR.bat`. Drag & Drop a base folder on the batch file, then MultiPar will create or verify subfolders in the base folder.

The key is setting the PAR filename to be based on the folder name. You must check "Always use folder name for base filename" option in "Client behavior", then each PAR2 set is named by the folder.

When a GUI is closed, next GUI is opened with next folder. You may set an option in "Automated tasks" to close GUI automatically after creation. If you want to skip complete files at verification, you may set option to close GUI automatically after verification, too.

```
@ECHO OFF
SETLOCAL

REM check input path
IF "%~1"=="" GOTO End
IF NOT EXIST "%~1" (
ECHO The path does not exist.
GOTO End
)
IF NOT "%~x1"=="" (
ECHO The path is not folder.
GOTO End
)

SET multipar_path="path of MultiPar.exe"

REM recursive search of subfolders
PUSHD %1
ECHO "%1"
FOR /D /R %%G IN (*.*) DO CALL :ProcEach "%%G"
POPD

GOTO End

REM open MultiPar GUI
:ProcEach
IF EXIST "%~1\%~n1.par2" (
ECHO verify for %1
%multipar_path% /verify "%~1\%~n1.par2"
) else (
ECHO create for %1
%multipar_path% /create %1
)

GOTO :EOF

:End
ENDLOCAL
```
