### ISSUE TITLE
Fixed redundancy size

### ISSUE THREAD

**Issue by K2M74** [Yutaka-Sawada/MultiPar#69]
Can you increase the default new redundant size option? I want to set 5%, but sometimes it's too far apart (2%-7%).

Or add an input box next to it.Precise drag is a bit time consuming.

![2022-07-21_11-37-17](https://user-images.githubusercontent.com/50667472/180124903-fd36a629-5f50-4434-8ab6-3e7b3f603079.png)

**Comment by Yutaka-Sawada** [comment]
> Can you increase the default new redundant size option?

I changed the behavior of `RedundancyMax` setting on `MultiPar.ini`. You may write a favorite value on the .INI file. If you want 5%, add a following line.
```
RedundancyMax=5
```

I put the sample (gui_sample_2022-07-21.zip) in "MultiPar_sample" folder on [OneDrive](https://1drv.ms/u/s!AtGhNMUyvbWOg0cF2UHcs709Icv4?e=UUj7bE). You cannot change the setting on MultiPar GUI. I don't want to change GUI for rare usage.
