### ISSUE TITLE
Add the option to turn off automatic verification? Remember the base directory? 

### ISSUE THREAD

**Issue by huhiha** [Yutaka-Sawada/MultiPar#7]
Now when I open a *.par2 file, it automatically starts the verification. I can pause the process but can not stop it. 
I store the *.par2 files in different locations than the data files. So if I need to change the base directory before the verification. 
When the verification is not finished, I can't change the base directory. 
I have 2 suggestions:

1. Add the option to turn off automatic verification. 
Maybe under Options -> Client behaviour -> Verification and Repair optioins. 
When automatic verification is turned off, we can press a button to manually start verification.

2. Let the *.par2 files remember relative path of the data files, so that I can store the data and the *.par2 files in different folders(usually not far away in the directory tree), and that I don't need to change the base directory everytime I open the *.par2 files.

**Comment by Yutaka-Sawada** [comment]
> I store the *.par2 files in different locations than the data files.

This is interesting. You ware not a user of QuickPar. In the era of QuickPar, PAR2 files and source files must be in a same directory. I still put them together.

> When the verification is not finished, I can't change the base directory.

I don't know why you cannot wait the finish. It needs to verify PAR2 files anyway. After it reports that all source files are missing, you will change the base directory.

> Let the *.par2 files remember relative path of the data files

I'm lazy to try big change. You can set your favorite "base directory", when you open a PAR2 file with MultiPar. It's possible to set "relative path" also. You may refer "Command_GUI.txt" for options of MultiPar.exe.

I explain how to;
1) Create Shortcut of MultiPar.exe at first.
2) You may put the Shortcut in SendTo menu or PAR file's folder as Drag&Drop target.
3) Open Property of the Shortcut.
4) There is a box of "Target". (MultiPar.exe's full path)
5) Add ` /base "path of data files"` after `MultiPar.exe` in the box.
6) You can set relative path in the path.
7) When you use relative path, "Start in" becomes the base of relative path.
8) If you want relative path from a selected PAR file, empty the "Start in" box.

**Comment by Yutaka-Sawada** [comment]
I made an option to save & restore Base Directory for version 1.3.2.9. I wrote this notice for those who are interested in this topic.

Add below lines in "MultiPar.ini";
```
[Path]
MRUMax=5
```
You may change number of saved path upto `MRUMax=26`.
