### ISSUE TITLE
bat doesn't handle special folders correctly

### ISSUE THREAD

**Issue by K2M74** [Yutaka-Sawada/MultiPar#72]
Normal folders, it works just fine.
It does not correctly recognize folders like "asd.asd.asd".
![image](https://user-images.githubusercontent.com/50667472/182784456-53fe2a84-c0be-49fa-b1c5-68b26dd920e9.png)

    @ECHO OFF
    chcp 65001
    SETLOCAL
    
    SET par2_path="%USERPROFILE%\AppData\Portable\MultiPar\par2j64.exe"
    
    :GetFilePath
    REM check input path
    IF "%~1"=="" GOTO End
    IF NOT EXIST "%~1" GOTO NextFile
    IF NOT "%~x1"=="" GOTO NextFile
    
    REM run PAR2 client
    ECHO create for %1
    %par2_path% c /fo /sm100000 /sr5 /rr5 /uo /up /rd2 /lp1 /lc32 "%~1\%~n1.par2" *
    
    IF ERRORLEVEL 1 GOTO End
    
    :NextFile
    SHIFT
    GOTO GetFilePath
    
    :End
    ENDLOCAL
    
    pause
    
I don't know how to modify it....

**Comment by Yutaka-Sawada** [comment]
> It does not correctly recognize folders like "asd.asd.asd".

I use "%~x1" to get a file's extension. When there is no extension, it recognizes the path as a folder. Thus, it failed, if the folder has extension (form of something.extesnsion).

I found [a page about Windows batch file](https://ss64.com/nt/syntax-args.html) in English. If you name folder with extension, you may use %~z1 to check folder. Or, just remove the checking line.

```
:GetFilePath
REM check input path
IF "%~1"=="" GOTO End
IF NOT EXIST "%~1" (
ECHO The path does not exist.
GOTO NextFile
)
IF NOT "%~z1"=="0" (
ECHO The path isn't folder.
GOTO NextFile
)
```

**Comment by K2M74** [comment]
> IF NOT "%~z1"=="0" (

It still didn't work, I modified it to.

    IF NOT "%~a1"=="d----------" (

Now it works, but I'm not sure if it's correct, sorry, I can't batch.

**Comment by K2M74** [comment]
> It still didn't work, I modified it to.

The reason is that some folders show a size of 4096.

**Comment by K2M74** [comment]
Now there is a new problem, when there is a folder that is empty, par2j64.exe will show input file is not found and then stop working, maybe it can be made to ignore the empty folder.

**Comment by Yutaka-Sawada** [comment]
> It still didn't work, I modified it to.

Oh, I see. It seems that size of folder refers disk space of internal files. It may be good to erase the line of checking specified path. It's difficult to check path in batch file. Users need to care by themsevles.

**Comment by K2M74** [comment]
> maybe it can be made to ignore the empty folder.

    :GetFilePath
    REM check input path
    IF "%~1"=="" GOTO End
    IF NOT EXIST "%~1" (
    ECHO The path does not exist.
    GOTO NextFile
    )

    IF NOT "%~a1"=="d----------" (
    ECHO The path is not folder.
    GOTO NextFile
    )

    REM delete empty directory.
    for /f "delims=" %%a in ('dir /ad /b /s ".\"^|sort /r') do (
      rd "%%a">nul 2>nul &&echo "%~1""%%a"Successfully deleted！
    )

**Comment by K2M74** [comment]
> maybe it can be made to ignore the empty folder.

    @ECHO OFF
    chcp 65001
    SETLOCAL
    
    SET par2_path="%USERPROFILE%\AppData\Portable\MultiPar\par2j64.exe"
    
    REM delete empty directory.
    for /f "delims=" %%a in ('dir "%~1" /ad /s /b') do (
        dir /a-d/s/b "%%~a\*" >nul 2>nul
        if errorlevel 1 (
            rd /s /q "%%~a" 2>nul && echo Successfully deleted "%%~a" || echo failed to delete "%%~a"
        )
    )
    
    :GetFilePath
    REM check input path
    IF "%~1"=="" GOTO End
    IF NOT EXIST "%~1" (
    ECHO The path does not exist.
    GOTO NextFile
    )
    IF NOT "%~a1"=="d----------" (
    ECHO The path isn't folder.
    GOTO NextFile
    )
    
    REM run PAR2 client
    ECHO create for %1
    %par2_path% c /sm100000 /sr5 /rr5 /uo /up /rd2 /lp1 /lc32 "%~1\%~n1.par2" *
    
    IF ERRORLEVEL 1 GOTO End
    
    :NextFile
    SHIFT
    GOTO GetFilePath
    
    :End
    ENDLOCAL
    
    pause

**Comment by Yutaka-Sawada** [comment]
I learn Python a little. I wrote a Python script to do same task. It will be more flexible than Batch script.

```
import sys
import os
import subprocess


# Return sub-process's ExitCode
def command(cmd):
    ret = subprocess.run(cmd, shell=True)
    return ret.returncode


# Return total size of internal files
def get_dir_size(path='.'):
    total = 0
    with os.scandir(path) as it:
        for entry in it:
            if entry.is_file():
                total += entry.stat().st_size
            elif entry.is_dir():
                total += get_dir_size(entry.path)
    return total


# Set path of par2j
client_path = "C:\\Test\\par2j64.exe"

# List of all arguments
#print('sys.argv:', sys.argv)

# Read arguments of command-line
for idx, arg in enumerate(sys.argv[1:]):
    one_path = arg
    one_name = os.path.basename(one_path)

    # Check the folder exists
    if os.path.isdir(one_path) == True:

        # Check empty folder
        if get_dir_size(one_path) > 0:
            print(one_name + " is folder.")

            # Path of creating PAR file
            # Cover by " for possible space
            par_path = one_path + "\\" + one_name + ".par2"

            # Check the PAR file exists already
            if os.path.exists(par_path) == True:
                print(one_name + " includes PAR file already.")

            else:
                # Set command-line
                # Cover path by " for possible space
                cmd = "\"" + client_path + "\" c /sm100000 /sr5 /rr5 /uo /up /rd2 /lp1 /lc32 \"" + par_path + "\" *"

                # Process the command
                print("Creating PAR files.")
                error_level = command(cmd)

                # Check error
                # Exit loop, when error occur.
                if error_level > 0:
                    print("Error = ", error_level)
                    break

        else:
            print(one_name + " is empty folder.")

    else:
        print(one_name + " isn't folder.")

# If you don't confirm result, comment out below line.
input('Press [Enter] key to continue . . .')
```
