### ISSUE TITLE
[Request] Can I include MultiPar binary into ngPost package?

### ISSUE THREAD

**Issue by mbruel** [Yutaka-Sawada/MultiPar#8]
Hi,
I didn't find where to contact you elsewhere so I'm doing it here...
I'm the dev of [ngPost](https://github.com/mbruel/ngPost), and I'm planing for the next release to make it easier for the users to choose between the different tools to generate par2. Currently I'm only embedding par2cmdline which is in public domain.
I'll include a compiled version of [ParPar](https://github.com/animetosho/ParPar) as it's much faster and the owner agreed I could do it.
Some people on windows use your soft, so I should probably make it available also. Would it be ok with you?
Do you provide both a 64bit and 32bit version?
May I ask in what language it is coded? Couldn't you build it for Linux and Mac?
Have you benchmark it against [ParPar](https://github.com/animetosho/ParPar/releases/download/v0.3.1/parpar.v0.3.1.win64.7z)? is it much faster?

**Comment by Yutaka-Sawada** [comment]
> Would it be ok with you?

I'm ok. But, I'm not sure that it's worth to include. There are MultiPar GUI (MultiPar.exe) and PAR2 clients (par2j.exe and par2j64.exe). At this case, you may put my PAR2 client for your usage. As a PAR2 client, mine is not so fast nowadays, because both par2cmdline and ParPar support multi-threading. The best point of MultiPar is the easy to use GUI.

> Do you provide both a 64bit and 32bit version?

Yes, I have. par2j.exe is 32-bit version. par2j64.exe is 64-bit version. For new CPU (Haswell or later), there are DLL for AVX2 support. par2j_extra.dll is 32-bit version. par2j64_extra.dll is 64-bit version. If you want speed for such CPU, put the DLL in same folder of EXE file. 

> May I ask in what language it is coded?

I use Microsoft Visual C 9 (Visual Studio 2008). The language is not C++, but it's normal C. To support old PCs, I use the old compiler.

> Couldn't you build it for Linux and Mac?

Mine doesn't support Linux or Mac. There are par2cmdline and ParPar for them.

> Have you benchmark it against ParPar? is it much faster?

I didn't test ParPar on my PC. (My PC is too old to use ParPar's new feature.) From the nature of CPU assembly code, ParPar should be faster than MultiPar, especially on recent CPUs. But one unknown point is GPU acceleration. Only when you have a very fast GPU, my PAR2 client may become faster. Because I don't have such fast GPU, I don't know the comparison.

**Comment by JohnLGalt** [comment]
> 
> 
> > Would it be ok with you?
> 
> I'm ok. But, I'm not sure that it's worth to include. There are MultiPar GUI (MultiPar.exe) and PAR2 clients (par2j.exe and par2j64.exe). At this case, you may put my PAR2 client for your usage. As a PAR2 client, mine is not so fast nowadays, because both par2cmdline and ParPar support multi-threading. The best point of MultiPar is the easy to use GUI.
> 
> > Do you provide both a 64bit and 32bit version?
> 
> Yes, I have. par2j.exe is 32-bit version. par2j64.exe is 64-bit version. For new CPU (Haswell or later), there are DLL for AVX2 support. par2j_extra.dll is 32-bit version. par2j64_extra.dll is 64-bit version. If you want speed for such CPU, put the DLL in same folder of EXE file.
> 
> > May I ask in what language it is coded?
> 
> I use Microsoft Visual C 9 (Visual Studio 2008). The language is not C++, but it's normal C. To support old PCs, I use the old compiler.
> 
> > Couldn't you build it for Linux and Mac?
> 
> Mine doesn't support Linux or Mac. There are par2cmdline and ParPar for them.
> 
> > Have you benchmark it against ParPar? is it much faster?
> 
> I didn't test ParPar on my PC. (My PC is too old to use ParPar's new feature.) From the nature of CPU assembly code, ParPar should be faster than MultiPar, especially on recent CPUs. But one unknown point is GPU acceleration. Only when you have a very fast GPU, my PAR2 client may become faster. Because I don't have such fast GPU, I don't know the comparison.

I just built a new PC (finally!) and had no idea there were faster versions of the CLI tools out there.  I've been faithfully using MP for a while now.

I replaced a Core i7 965 EE on X58 Chipset-based motherboard with Ryzen 9 3950x on X570-based motherboard with gobs of RAM and NVMe storage.  My GPU is currently GTX970 as I'm awaiting the new Ampere graphics card launch in a couple of weeks.  As it is, MP on this new system is able to both verify and fix files, even large ones, extremely quickly compared to the old system.

I'm assuming the other CLI tools have different parameters and arguments, so it's not just a matter of perhaps renaming them to your included tools' names and using them in place - the GUI simply would not (necessarily) work.  But if you did ever modify your code for the GUI to make use of these other CLI tools, I'd be happy to help test.

**Comment by mbruel** [comment]
@Yutaka-Sawada sorry for the late reply, I took some vacation away from my laptop ;)

> I'm ok. But, I'm not sure that it's worth to include. There are MultiPar GUI (MultiPar.exe) and PAR2 clients (par2j.exe and par2j64.exe). At this case, you may put my PAR2 client for your usage. As a PAR2 client, mine is not so fast nowadays, because both par2cmdline and ParPar support multi-threading. The best point of MultiPar is the easy to use GUI.

yes I'd only add the par2 client. I don't think par2cmdline is multi-threaded. ParPar is and it's quite fast. I never tried par2j cause I neither have Windows not a decent graphic card. If you have both, I'm really wondering if using the graphic card is faster than the multi-threaded CPU only. Some people continue to use par2j so I guess it can...



>  If you want speed for such CPU, put the DLL in same folder of EXE file.

ok will do :+1: 




> The language is not C++, but it's normal C. To support old PCs, I use the old compiler.

if the language is pure C, can't you compile it on Unix with gcc? What parts are linked to Windows OS? only the file management? I guess the Visual part is only for the GUI right?



> Only when you have a very fast GPU, my PAR2 client may become faster. Because I don't have such fast GPU, I don't know the comparison.

yeah it would be great to have some benchmarks with the latest GPUs against a Core i7 or even a xeon with 32 cores.

**Comment by mbruel** [comment]
@JohnLGalt 

> As it is, MP on this new system is able to both verify and fix files, even large ones, extremely quickly compared to the old system.

Well can you provide a benchmark. Let's say to generate 5% of par2 for a 50GB image.
If you could the same with [ParPar](https://github.com/animetosho/ParPar), [here is the win64 compiled](https://github.com/animetosho/ParPar/releases/download/v0.3.1/parpar.v0.3.1.win64.7z) version, the syntax is simple but you've to do it in command line. `parpar -s 1M -r5% yourFile`





> I'm assuming the other CLI tools have different parameters and arguments, so it's not just a matter of perhaps renaming them to your included tools' names and using them in place - the GUI simply would not (necessarily) work. But if you did ever modify your code for the GUI to make use of these other CLI tools, I'd be happy to help test.

yes I know. I'm already supporting both par2cmdline and ParPar for basic features. I'd be happy to add par2j. For more complicated parameters, you'd be able to add options in a text field ;)

**Comment by Yutaka-Sawada** [comment]
> I don't think par2cmdline is multi-threaded.

[Recent versions of par2cmdline](https://github.com/Parchive/par2cmdline) support OpenMP for multi-threading. 
There is an option like below;
`-t<n> : Number of threads to use (Auto-detected)`

> can't you compile it on Unix with gcc? What parts are linked to Windows OS? only the file management? I guess the Visual part is only for the GUI right?

It's not pure C. The source code is hard to use on Unix, because I use Win32API.

**Comment by JohnLGalt** [comment]
> 
> 
> @JohnLGalt
> 
> > As it is, MP on this new system is able to both verify and fix files, even large ones, extremely quickly compared to the old system.
> 
> Well can you provide a benchmark. Let's say to generate 5% of par2 for a 50GB image.
> If you could the same with [ParPar](https://github.com/animetosho/ParPar), [here is the win64 compiled](https://github.com/animetosho/ParPar/releases/download/v0.3.1/parpar.v0.3.1.win64.7z) version, the syntax is simple but you've to do it in command line. `parpar -s 1M -r5% yourFile`
> 
> > I'm assuming the other CLI tools have different parameters and arguments, so it's not just a matter of perhaps renaming them to your included tools' names and using them in place - the GUI simply would not (necessarily) work. But if you did ever modify your code for the GUI to make use of these other CLI tools, I'd be happy to help test.
> 
> yes I know. I'm already supporting both par2cmdline and ParPar for basic features. I'd be happy to add par2j. For more complicated parameters, you'd be able to add options in a text field ;)

I attempted to use the same parameters as were used in the examples posted on the parpar git, but the files, file size, and other things were not even remotely the same.  I suspect that either the parameters have changed, or the arguments ahve changed, or something is strange.

Using Yutaka's par2j64 (directly in the Multipar Folder) and following the examples given from parpar's benchmark page, parpar worked perfectly fine, but using the same commands with par2j64 created a weird single file, and some funkiness with the file size and whatnot.

I have a 68GB .7z file of a small subset of my music library that I can easily test - but I have to get hte parameters correct for par2j64 to make sure that it is actually performing the same sort of file generation that I have parpar doing.

Regardless, though, it does seem parpar is extremely fast, and it makes sense as with what Yutaka said about recent CPUs.

However, I do 80% verification and 20% creation, so it's never really been an issue - verification is fast with MP.  Creation though - I'm almost positive that parpar is going to be much, much faster.

A GUI (like MP) for parpar would be fantabulous, as it is easier than manually entering parameters every time.  Even with a batch file, it takes a bit of playing around until you get it just right.

I'lll continue to try to benchmark that large 68GB file and if I can get standardized results from both executables, I'll post back with screenshots and explanation.
