### ISSUE TITLE
Option from right click to create a unique PAR Files for each folder or files if multi folders or multi files selected

### ISSUE THREAD

**Issue by DEVUVO** [Yutaka-Sawada/MultiPar#80]
Hello , can you please make an option to create par per file and per folder if i select multi folders at the same time and files will be generate inside each folder for example 

if i have 2000 folder and i need each folder to have it's PAR files inside it 
and for single files if selected multi files will be able to get a par files for each file 

the current app i can create par files for a folder but one at a time if i choose 2 folders it will add all files from both folder to multipar and then make par files for all the files

thanks in advance.

**Comment by Yutaka-Sawada** [comment]
It will be good to use batch file. But, the task is a bit complex, because you may select both folders and files. My written batch scripts were for either folders or files. I didn't consider the mixed usage. You may read those samples over Help documents of MultiPar.

Now, I normaly use Python script instead of Batch file. Though I can write a sample Python script, you need to install Python language to use it. Furthermore, you need to modify command-line options of par2j for your favorite settings. If it's OK, I will write and upload the sample.

**Comment by DEVUVO** [comment]
Yes please , i will use folders or files , not both at the same time , is it possible to add a tick box to the GUI , i can install Python but i need details too if it's hard i always stay away from cmd commands sorry but i can try if you attached some details to make it work , thanks.

**Comment by Yutaka-Sawada** [comment]
I put a sample Python script (script_sample_2023-01-13.zip) in "MultiPar_sample" folder on [OneDrive](https://1drv.ms/u/s!AtGhNMUyvbWOg0cF2UHcs709Icv4). Please test the behavior. To use it, it may be good to read MultiPar help documents. If there is a problem or something requested feature, I will modify more.

**Comment by DEVUVO** [comment]
Thanks , I did everything like you said but when i select 2 folder for testing and clicking start it will show nothing in the CMD window , if i select one folder only it will create PAR set for each file inside this folder , maybe there is something wrong 

![2023-01-15_001900](https://user-images.githubusercontent.com/51355263/212499662-d53e5f52-d917-44d5-a6b5-957f46a3ee2c.png)


---------------------


Can you please make make the command create PAR set for all the files inside this folder

I think it's confusing requesting such a thing.

**Comment by Yutaka-Sawada** [comment]
> when i select 2 folder for testing and clicking start it will show nothing in the .py window

I fixed the bug. I updated the sample Python script (script_sample_2023-01-15.zip) in "MultiPar_sample" folder on [OneDrive](https://1drv.ms/u/s!AtGhNMUyvbWOg0cF2UHcs709Icv4). I added 2 buttons to add folder or file manually.

> Can you please make make the command create PAR set for all the files inside this folder
> I think it's confusing requesting such a thing.

I'm not sure your usage. You should post examples of what you want. What result for which case.

(A) When you select 2 folders (for example, Folder1 and Folder2), and send to PARQueue, every folders are listed.
Then, it will create Folder1.par2 in Folder1. The par2 set (Folder1.par2) protects all files in the Folder1.
It will create Folder2.par2 in Folder2. The par2 set (Folder2.par2) protects all files in the Folder2.

(B) When you select 1 folder (for example, "Camera Roll"), and send to PARQueue, it's treated as parent folder.
Then, all children folders and files in the folder are listed. In the example, there are 2 files "desktop.ini" and "WIN_20230110_13_55_11_Pro.mp4" in "Camera Roll" folder. It will create PAR set for each item.

If you want to create one PAR set for all files in one folder, just use MultiPar. You can put short-cut of MultiPar in right-click SendTo menu.

**Comment by DEVUVO** [comment]
Thanks , but as you can see the start button is dimmed and cant use it when i select 2 folders as you can see


![2023-01-16_170811](https://user-images.githubusercontent.com/51355263/212709979-db8569e8-04b3-46c7-bcc3-318cbd371e04.png)

**Comment by Yutaka-Sawada** [comment]
> but as you can see the start button is dimmed and cant use it when i select 2 folders as you can see

Oh, I'm sorry for my mistake sometimes. I made another bug, when I tried to fix a bug. This time, I fixed the bug, maybe hehe.

I put the updated sample Python script (script_sample_2023-01-17.zip) in "MultiPar_sample" folder on [OneDrive](https://1drv.ms/u/s!AtGhNMUyvbWOg0cF2UHcs709Icv4). If you see a bug or problem still, please report again.

**Comment by DEVUVO** [comment]
LOL , here you go again , When i select 2 folders nothing happened after i click start , if i want to make par set to 2 folders i have to cut the folders into a single folder and select that folder to get par files for each folder inside the folder i just choose ,

so If i want to make pars for folder named AAA & BBB

I have to move both folder inside folder KKK then run start the command will make pars for AAA and BBB , so there is something wrong  still 📄

**Comment by Yutaka-Sawada** [comment]
I'm not sure how is your usage. I designed it to create PAR files for children of a folder. It may not work well in other cases. Please show example of bad case. Then, I will test the behavior and fix the problem.

Such like; directory tree of files, how to select files/folders, what is bad result, and what good result should be.

**Comment by DEVUVO** [comment]
Thanks for being awesome with explaining , I do need to select 2 folders for example from right click or send to the .py shortcut

so if i have folder AAAAA and BBBBBB

these 2 folder have no children or sunfolders inside them i just want to make pars for each folder and the par file will be inside each folder , thats all

if it's possible you can add this option to the tree folder script you just did or make a new one under different name

thanks

**Comment by Yutaka-Sawada** [comment]
> so if i have folder AAAAA and BBBBBB

Where are these folders ? Do they exist in different directories ? When you select multiple folders or files, they would exist under a same directory.

> these 2 folder have no children or sunfolders inside them

When the folder doesn't contain files, PAR files won't be made. To create PAR files, each folder must include at least one file.

**Comment by DEVUVO** [comment]
> Where are these folders ? Do they exist in different directories ? When you select multiple folders or files, they would exist under a same directory.

these folders are in different location , i use everything tool to search for multiple folder at once , can you please make something to work with folders in diff locations

the folders for sure have files inside it , 

thank you

**Comment by Yutaka-Sawada** [comment]
> these folders are in different location

I see. That was why it didn't work. When there is a problem, detail of the case is important to solve. I modified my script to support different locations. Because it stores full path, don't use relative path. (Drag & Drop or SendTo would specify full path normally.)

I put the sample Python script (script_sample_2023-01-28.zip) in "MultiPar_sample" folder on [OneDrive](https://1drv.ms/u/s!AtGhNMUyvbWOg0cF2UHcs709Icv4). When something wrong, it may show error message as status text. If you see a bug or problem, please report with detail.

**Comment by DEVUVO** [comment]
Just perfect , Thank you so much . You the man :)

PerrrrFECT

**Comment by Yutaka-Sawada** [comment]
You are welcome.

I will include the script to MultiPar at next version. I need to write help documents of how to use it. (That is a lazy task, hehe.)

**Comment by DEVUVO** [comment]
you the man , I can now drag drop , i cant wait for the MP next version then , PERFECT.
