### ISSUE TITLE
Preserve files timestamps 

### ISSUE THREAD

**Issue by Stepan-H** [Yutaka-Sawada/MultiPar#81]
Similar like 7zip, it has a function preservation timestamps of creation, modification and last access.

When restoring the file, it would be perfect if the original timestamp of Last Modification and timestamp of Creation will be preserved.

Preservation timestamp of Last Modification is crucial, because Last Modification indicate "version" (figuratively speaking) of files.

Preservation timestamp of Creation is not necessary but it woud be nice to preserve it, because when you copy files, you lost it and Creation indicate datetime of "first version" (figuratively speaking) of files.

There is also Last Access, but it "still" changes by accesing and preserve this so much dynamic information is useless perhaps even counterproductive.

**Comment by Yutaka-Sawada** [comment]
PAR2 doesn't have such feature. Next PAR3 will have the timestamp. (There is a sample already [at here](https://github.com/parchive/par3cmdline).) So, I don't add timestamp on current PAR2.
