### ISSUE TITLE
How do you install this?  There is no install file.

### ISSUE THREAD

**Issue by jsmwrench** [Yutaka-Sawada/MultiPar#83]
I downloaded the .zip file and 'extracted all', but did not find any kind of install file.

**Comment by Yutaka-Sawada** [comment]
If you want to install MultiPar by using installer, you must download .EXE file instead of .ZIP file. The file has name such like `MultiPar1326_setup.exe` on [Release page](https://github.com/Yutaka-Sawada/MultiPar/releases).

**Comment by jsmwrench** [comment]
Thank you for responding.  I did find it, but this is different than all of the other code that I've downloaded.  Anyway, I think this one can be closed.  Thank you again.
