### ISSUE TITLE
Compile source on Ubuntu?

### ISSUE THREAD

**Issue by gareth41** [Yutaka-Sawada/MultiPar#94]
I'm trying to compile the source on Ubuntu but there is no makefile in the source tar.gz or any other configuration scripts, is there a way to do this?  Thanks in advance.

**Comment by Yutaka-Sawada** [comment]
> is there a way to do this?

No, you cannot compile it on Linux. Because my source code uses Microsoft C (Visual Studio) and Win32 API, it runs only on Windows OS. If you want to use a fast PAR2 client on Linux, you may try [speed focused par2cmdline](https://github.com/animetosho/par2cmdline-turbo).
