### ISSUE TITLE
GitHub account restriction

### ISSUE THREAD

**Issue by Yutaka-Sawada** [Yutaka-Sawada/MultiPar#97]
I got a notice from GitHub, which requires 2FA to users. Though GitHub wants to enforce 2FA, it's impossible for me. Then, my account actions will be restricted after October 12, 2023.

I don't know which action will be refused. So, I wait what will happen and think how to do later. If I won't be able to use GitHub anymore, I may need to find another public space.

At this time, I use [Vector.co.jp](https://hp.vector.co.jp/authors/VA021385/) for annoucement, and put files on [OneDrive](https://1drv.ms/u/s!AtGhNMUyvbWOaSo1n_R8awJ_hg0). When [my GitHub page](https://github.com/Yutaka-Sawada/) will disapper in future, please see these web-sites. I'm sorry for the inconvenience.

**Comment by gareth41** [comment]
You shouldn't be making it public that your account doesn't use 2FA, you're setting yourself up as a target.

If you don't have access to a mobile device that can use the Authenticator apps, you can still use a desktop app like Keepass to generate the 2FA code

**Comment by Yutaka-Sawada** [comment]
Oh, I see. When something wrong happens, I will leave GitHub.

**Comment by animetosho** [comment]
It's unfortunate that they decided to *force* usage of 2FA - I don't like being forced to do things I'd rather not.  
(then again, I disagree with a lot of "best practices" surrounding IT security)

As mentioned, you can give KeepassXC a try. It's an annoying extra step, but maybe you can configure it to not be too bad.  
If that doesn't work for you, I suggest updating the README with those links, before you get locked out.  
From my understanding, this repository won't disappear, you just won't be able to update/change certain things.
